import { useState } from 'react';
import { Search, Truck } from 'lucide-react';
import { AdminApi } from '../api/adminApi';
import { Page, InputField } from './adminShared';
import { useAdminData, panel, field, formValues } from './adminState';
import { Button } from '../../../components/ui/Button';

export function AdminShippingView() {
  const state = useAdminData();
  const db = state.db;
  const [search, setSearch] = useState('');
  const shipments = (db?.orders ?? []).filter(o => o.status === 'shipped' && `${o.orderNumber} ${o.courier} ${o.tracking?.receiptNumber ?? ''}`.toLowerCase().includes(search.toLowerCase()));
  return <Page title="Manajemen Pengiriman" state={state}>
    <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_360px]">
      <section className={`${panel} min-w-0`}><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold">Pengiriman aktif</h3><p className="text-xs text-slate-500">{shipments.length} pengiriman ditampilkan</p></div><label className="relative w-full sm:w-64"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input aria-label="Cari pengiriman" placeholder="Cari order, kurir, atau resi" value={search} onChange={e => setSearch(e.target.value)} className={`${field} pl-9`} /></label></div>
        <div className="divide-y divide-slate-100 dark:divide-slate-800">{shipments.map(o => <article key={o.id} className="space-y-3 py-5 first:pt-0"><div className="flex flex-wrap justify-between gap-3"><div><h4 className="font-mono font-semibold text-orange-600 dark:text-orange-400">{o.orderNumber}</h4><p className="mt-1 text-sm">{o.courier}</p><p className="text-xs text-slate-500">Resi: {o.tracking?.receiptNumber ?? 'Belum tersedia'}</p></div><span className="h-fit rounded-full bg-blue-50 px-3 py-1 text-xs font-medium text-blue-700 dark:bg-blue-950 dark:text-blue-300">{o.tracking?.currentStatus ?? o.status}</span></div><ol className="space-y-3 border-l-2 border-orange-200 pl-4 dark:border-orange-900">{o.tracking?.timeline.map(t => <li key={t.id}><p className="text-xs text-slate-500">{new Date(t.timestamp).toLocaleString('id-ID')}</p><p className="text-sm">{t.description}</p></li>)}</ol></article>)}{!shipments.length && <div className="py-10 text-center"><Truck className="mx-auto mb-3 text-orange-400" /><p className="font-medium">{search ? 'Pengiriman tidak ditemukan' : 'Tidak ada pengiriman aktif'}</p><p className="mt-1 text-sm text-slate-500">{search ? 'Coba kata kunci order atau nomor resi lainnya.' : 'Pesanan yang sudah dikirim akan tampil di sini.'}</p></div>}</div><p className="rounded-xl bg-slate-50 p-3 text-xs text-slate-500 dark:bg-slate-900 dark:text-slate-400">Tracking lokal, tidak terhubung GPS atau API kurir. Perbarui status melalui detail pesanan.</p>
      </section>
      <div className="space-y-5">{db && <form className={panel} onSubmit={e => { const data = formValues(e); void state.run(() => AdminApi.saveSettings({...db.settings,shippingFee:Number(data.get('fee'))})); }}><h3 className="font-semibold">Ongkir default</h3><p className="text-sm text-slate-500">Biaya pengiriman bawaan untuk checkout.</p><InputField label="Biaya default (Rp)" name="fee" type="number" min={0} value={db.settings.shippingFee} /><Button disabled={state.busy}>Simpan ongkir</Button></form>}
        <form className={panel} onSubmit={e => { const form = e.currentTarget; const data = formValues(e); void state.run(() => AdminApi.saveCourier({id:'',name:String(data.get('name')),fee:Number(data.get('fee')),isActive:true})).then(ok => {if(ok) form.reset();}); }}><h3 className="font-semibold">Tambah kurir</h3><p className="text-sm text-slate-500">Kurir baru akan langsung berstatus aktif.</p><InputField label="Nama kurir" name="name" /><InputField label="Tarif (Rp)" name="fee" type="number" min={0} /><Button disabled={state.busy}>Tambah kurir</Button></form>
      </div>
    </div>
    <section className={panel}><h3 className="font-semibold">Pengaturan kurir</h3><p className="text-sm text-slate-500 dark:text-slate-400">Tarif tersimpan di repository. Subsidi ongkir dan wilayah layanan belum didukung checkout.</p><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{db?.shipping.map(c => <form key={`${c.id}-${c.fee}-${c.isActive}`} className="space-y-3 rounded-xl border border-slate-200 p-4 dark:border-slate-800" onSubmit={e => { const data = formValues(e); void state.run(() => AdminApi.saveCourier({...c,name:String(data.get('name')),fee:Number(data.get('fee')),isActive:data.get('active') === 'on'})); }}><InputField label="Nama kurir" name="name" value={c.name} /><InputField label="Tarif (Rp)" name="fee" type="number" min={0} value={c.fee} /><div className="flex flex-wrap items-center justify-between gap-3"><label className="flex items-center gap-2 text-sm"><input name="active" type="checkbox" defaultChecked={c.isActive} className="accent-orange-500" /> Aktif</label><Button size="sm" disabled={state.busy}>Simpan kurir</Button></div></form>)}</div>{!db?.shipping.length && <p className="py-4 text-sm text-slate-500">Belum ada kurir. Tambahkan kurir melalui formulir di atas.</p>}</section>
  </Page>;
}
