import { useState } from 'react';
import { useLocation } from 'react-router-dom';
import { Search, ShieldCheck, Users } from 'lucide-react';
import { AdminApi } from '../api/adminApi';
import { Page, InputField } from './adminShared';
import { useAdminData, panel, field, formValues, money } from './adminState';
import { Button } from '../../../components/ui/Button';

export function AdminTlaterRiskView() {
  const state = useAdminData();
  const location = useLocation();
  const [search, setSearch] = useState(() => new URLSearchParams(location.search).get('search') ?? '');
  const db = state.db;
  const customers = db?.customers.filter(c => c.role === 'customer' && `${c.name} ${c.email}`.toLowerCase().includes(search.toLowerCase())) ?? [];
  const applications = db?.kyc.filter(k => `${k.name} ${k.nik}`.toLowerCase().includes(search.toLowerCase())) ?? [];
  return <Page title="Pelanggan, KYC & Risiko TLater" state={state}>
    <div className={`${panel} flex flex-wrap items-center gap-3`}><label className="relative min-w-0 flex-1"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input aria-label="Cari pelanggan atau NIK" placeholder="Cari pelanggan, email, atau NIK" className={`${field} pl-9`} value={search} onChange={e => setSearch(e.target.value)} /></label><span className="text-xs text-slate-500">{customers.length} pelanggan · {applications.length} pengajuan KYC</span></div>
    <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_340px]">
      <div className="space-y-5"><section className={panel}><div className="flex items-center gap-2"><Users size={18} className="text-orange-500" /><h3 className="font-semibold">Pelanggan & Limit Akun</h3></div><p className="text-xs text-slate-500">Limit global berlaku untuk seluruh akun terverifikasi. Limit per akun dan suku bunga belum didukung.</p><div className="divide-y divide-slate-100 dark:divide-slate-800">{customers.map(c => {
        const used = db!.loans.filter(l => l.userId === c.id).reduce((s,l) => s + l.installments.filter(i => i.status !== 'paid').reduce((a,i) => a + i.principalDue,0),0);
        return <article key={c.id} className="space-y-3 py-4 first:pt-0 last:pb-0"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-semibold">{c.name}</p><p className="text-xs text-slate-500">{c.email} · {c.phone ?? '-'}</p></div><span className={`rounded-full px-2 py-0.5 text-xs font-medium ${c.kycStatus === 'verified' ? 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300' : 'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300'}`}>KYC {c.kycStatus}</span></div><div className="grid gap-2 rounded-xl bg-slate-50 p-3 text-xs sm:grid-cols-3 dark:bg-slate-900"><div><p className="text-slate-500">Limit global</p><p className="mt-1 font-semibold tabular-nums">{money(db!.settings.creditLimit)}</p></div><div><p className="text-slate-500">Terpakai</p><p className="mt-1 font-semibold tabular-nums">{money(used)}</p></div><div><p className="text-slate-500">Tersedia</p><p className="mt-1 font-semibold tabular-nums text-orange-600 dark:text-orange-400">{money(Math.max(0,db!.settings.creditLimit-used))}</p></div></div><p className="text-xs text-slate-500">ID {c.id} · {db!.points[c.id] ?? 0} poin · {db!.orders.filter(o => o.userId === c.id).length} pesanan</p></article>;
      })}{!customers.length && <p className="py-8 text-center text-sm text-slate-500">{search ? 'Pelanggan tidak ditemukan.' : 'Belum ada pelanggan.'}</p>}</div></section>
      <section className={panel}><div className="flex items-center gap-2"><ShieldCheck size={18} className="text-orange-500" /><h3 className="font-semibold">Review KYC</h3></div><div className="divide-y divide-slate-100 dark:divide-slate-800">{applications.map(k => <article key={k.userId} className="space-y-4 py-5 first:pt-0 last:pb-0"><div className="flex flex-wrap justify-between gap-2"><div><h4 className="font-semibold">{k.name}</h4><p className="text-xs text-slate-500">NIK {k.nik} · Lahir {k.dateOfBirth}</p></div><span className={`h-fit rounded-full px-2 py-0.5 text-xs ${k.status === 'pending' ? 'bg-amber-50 text-amber-700 dark:bg-amber-950 dark:text-amber-300' : 'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300'}`}>{k.status}</span></div><div className="space-y-1 text-xs"><p><span className="text-slate-500">Alamat:</span> {k.address}</p><p><span className="text-slate-500">Diajukan:</span> {new Date(k.submittedAt).toLocaleString('id-ID')}</p>{k.reason && <p><span className="text-slate-500">Alasan keputusan:</span> {k.reason}</p>}</div><div className="flex flex-wrap gap-3">{[k.ktpImageUrl,k.selfieImageUrl].map((url,i) => <a key={i} href={url} target="_blank" rel="noreferrer" className="overflow-hidden rounded-xl border border-slate-200 dark:border-slate-800"><img className="h-28 w-36 bg-slate-50 object-contain dark:bg-slate-900" src={url} alt={i ? 'Swafoto pemohon' : 'KTP pemohon'} /><span className="block border-t p-1 text-center text-xs dark:border-slate-800">{i ? 'Swafoto' : 'KTP'}</span></a>)}</div>{k.status === 'pending' && <form className="flex flex-wrap gap-2" onSubmit={e => { const data = formValues(e); void state.run(() => AdminApi.verifyKyc(k.userId,false,String(data.get('reason')))); }}><input name="reason" required aria-label="Alasan penolakan" placeholder="Alasan penolakan" className={`${field} min-w-44 flex-1`} /><Button type="submit" variant="outline" disabled={state.busy}>Tolak</Button><Button type="button" disabled={state.busy} onClick={() => void state.run(() => AdminApi.verifyKyc(k.userId,true))}>Setujui KYC</Button></form>}</article>)}{!applications.length && <p className="py-8 text-center text-sm text-slate-500">{search ? 'Pengajuan tidak ditemukan.' : 'Belum ada pengajuan KYC.'}</p>}</div></section></div>
      {db && <form className={`${panel} h-fit`} onSubmit={e => { const data = formValues(e); void state.run(() => AdminApi.saveSettings({...db.settings,creditLimit:Number(data.get('limit'))})); }}><h3 className="font-semibold">Limit Kredit Global</h3><p className="text-sm text-slate-500">Batas kredit yang berlaku untuk seluruh akun TLater terverifikasi.</p><InputField label="Limit (Rp)" name="limit" type="number" min={0} value={db.settings.creditLimit} /><Button disabled={state.busy}>Simpan Limit</Button></form>}
    </div>
  </Page>;
}
